/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatProjectIdRouteImport } from './routes/chat.$projectId'
import { Route as ApiNvidiaChatRouteImport } from './routes/api/nvidia-chat'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatProjectIdRoute = ChatProjectIdRouteImport.update({
  id: '/chat/$projectId',
  path: '/chat/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNvidiaChatRoute = ApiNvidiaChatRouteImport.update({
  id: '/api/nvidia-chat',
  path: '/api/nvidia-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/api/nvidia-chat': typeof ApiNvidiaChatRoute
  '/chat/$projectId': typeof ChatProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/api/nvidia-chat': typeof ApiNvidiaChatRoute
  '/chat/$projectId': typeof ChatProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/api/nvidia-chat': typeof ApiNvidiaChatRoute
  '/chat/$projectId': typeof ChatProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/skills'
    | '/api/nvidia-chat'
    | '/chat/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/skills' | '/api/nvidia-chat' | '/chat/$projectId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/skills'
    | '/api/nvidia-chat'
    | '/chat/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  ApiNvidiaChatRoute: typeof ApiNvidiaChatRoute
  ChatProjectIdRoute: typeof ChatProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$projectId': {
      id: '/chat/$projectId'
      path: '/chat/$projectId'
      fullPath: '/chat/$projectId'
      preLoaderRoute: typeof ChatProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nvidia-chat': {
      id: '/api/nvidia-chat'
      path: '/api/nvidia-chat'
      fullPath: '/api/nvidia-chat'
      preLoaderRoute: typeof ApiNvidiaChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  ApiNvidiaChatRoute: ApiNvidiaChatRoute,
  ChatProjectIdRoute: ChatProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
